version: 0.0
os: linux
files:
  - source: /app
    destination: /opt/app
hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 120
      runas: root
    - location: scripts/remove.sh
      timeout: 120
      runas: root
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 120
      runas: root
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 120
      runas: root